version: '3'
services:
  web_server:
    build:
      context: ./web_server/
    container_name: apache2
    depends_on:
      - db
    volumes:
      - ./magento2:/var/www/html
      - ./web_server/000-default.conf:/etc/apache2/sites-enabled/000-default.conf
    ports:
      - "8000:80"
    links:
      - db
  db:
    image: mariadb
    ports:
      - "3308:3306"
    volumes:
      - ./dbdata:/var/lib/mysql
    environment:
      - MYSQL_ROOT_PASSWORD=magento2
      - MYSQL_DATABASE=magento2
      - MYSQL_USER=magento2
      - MYSQL_PASSWORD=magento2
